# Generated by Django 3.1 on 2020-09-01 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=32)),
                ('public_ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=500, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_probe_at', models.DateTimeField(auto_now=True)),
                ('last_boot_at', models.DateTimeField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=20, null=True)),
                ('platform', models.CharField(blank=True, max_length=150, null=True)),
                ('platform_family', models.CharField(blank=True, max_length=150, null=True)),
                ('platform_version', models.CharField(blank=True, max_length=150, null=True)),
                ('kernel_version', models.CharField(blank=True, max_length=20, null=True)),
                ('kernel_architecture', models.CharField(blank=True, max_length=20, null=True)),
                ('virtualization_system', models.CharField(blank=True, max_length=150, null=True)),
                ('virtualization_role', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('executable', models.CharField(max_length=255)),
                ('command_line', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('monitored', models.BooleanField(default=False)),
                ('monitored_since', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Running'), ('S', 'Sleep'), ('T', 'Stop'), ('I', 'Idle'), ('Z', 'Zombie'), ('W', 'Wait'), ('L', 'Lock')], default='R', max_length=1)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('A', 'Seen'), ('B', 'Signal caught'), ('C', 'CPU threshold reached'), ('D', 'Memory threshold reached'), ('E', 'Suspected hang caught'), ('F', 'Exited'), ('G', 'Not found')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caught_signal', models.IntegerField(blank=True, null=True)),
                ('cpu_usage', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.IntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('core_dump_location', models.URLField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.process')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('detect_signals', models.BooleanField(default=False)),
                ('detect_thresholds', models.BooleanField(default=False)),
                ('detect_suspected_hangs', models.BooleanField(default=False)),
                ('cpu_threshold', models.IntegerField(blank=True, null=True)),
                ('memory_threshold', models.IntegerField(blank=True, null=True)),
                ('suspected_hang_duration', models.DurationField(blank=True, null=True)),
                ('restart_on_signal', models.BooleanField(default=True)),
                ('restart_on_cpu_threshold', models.BooleanField(default=False)),
                ('restart_on_memory_threshold', models.BooleanField(default=False)),
                ('restart_on_suspected_hang', models.BooleanField(default=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.process')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
