# Generated by Django 3.1 on 2020-08-16 15:12

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=500, null=True)),
                ('last_activity', models.CharField(max_length=150)),
                ('last_activity_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('executable', models.CharField(max_length=255)),
                ('command_line', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('monitored', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('monitored_since', models.DateTimeField(blank=True, null=True)),
                ('disappeared_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(
                    choices=[('A', 'Seen'), ('B', 'Signal caught'), ('C', 'CPU threshold reached'),
                             ('D', 'Memory threshold reached'), ('E', 'Suspected hang caught'), ('F', 'Exited'),
                             ('G', 'Not found')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caught_signal', models.IntegerField(blank=True, null=True)),
                ('cpu_usage', models.IntegerField(blank=True, null=True)),
                ('memory_usage', models.IntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('core_dump_location', models.URLField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitor_signals', models.BooleanField(default=False)),
                ('monitor_thresholds', models.BooleanField(default=False)),
                ('monitor_suspected_hangs', models.BooleanField(default=False)),
                ('cpu_threshold', models.IntegerField(blank=True, null=True)),
                ('memory_threshold', models.IntegerField(blank=True, null=True)),
                ('suspected_hang_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.process')),
            ],
        ),
    ]
