# Generated by Django 3.1 on 2020-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0002_processconfiguration_restart_on_crash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(default='1.2.3.4'),
            preserve_default=False,
        ),
    ]
