# Generated by Django 3.1 on 2020-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20200901_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionconfig',
            name='is_relevant',
            field=models.BooleanField(default=True),
        ),
    ]
