# Generated by Django 3.1 on 2020-08-23 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('hosts', '0006_auto_20200823_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='status_updated_at',
            new_name='last_keepalive_at',
        ),
        migrations.RemoveField(
            model_name='host',
            name='status',
        ),
    ]
