# Generated by Django 3.1 on 2020-08-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200816_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='api_key',
        ),
    ]
