# Generated by Django 3.1 on 2020-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processconfiguration',
            name='restart_on_crash',
            field=models.BooleanField(default=True),
        ),
    ]
