# Generated by Django 3.1 on 2020-08-23 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20200819_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='last_activity_at',
            new_name='status_updated_at',
        ),
        migrations.RemoveField(
            model_name='host',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='host',
            name='last_reboot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('A', 'Seen'), ('B', 'Gone')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
