# Generated by Django 3.1 on 2020-08-23 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20200823_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='ip_address',
            new_name='public_ip_address',
        ),
        migrations.AddField(
            model_name='host',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
