# Generated by Django 3.1 on 2020-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_auto_20200823_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='kernel_architecture',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='kernel_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='platform',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='platform_family',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='platform_version',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='virtualization_role',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='virtualization_system',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
