# Generated by Django 3.1 on 2020-08-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_auto_20200823_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='operating_system',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
