# Generated by Django 3.1 on 2020-08-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_host_operating_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='machine_id',
            field=models.CharField(default='7fash8h347fhdsa7f74fsf', max_length=150),
            preserve_default=False,
        ),
    ]
